#!/bin/bash

set -e
echo "Fetching training data..."
for i in $(seq 1 6);
do
    name="enron$i.tar.gz"
    wget http://www.aueb.gr/users/ion/data/enron-spam/preprocessed/$name --no-check-certificate 
    echo "Unzipping $name..."
    tar -xzf $name 
    echo "Deleting $name..."
    rm -rf $name
done
